apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ucsb1hjn8-go 
  janus-idp.io/tekton: ucsb1hjn8-go
  backstage.io/kubernetes-id: ucsb1hjn8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ucsb1hjn8-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  