apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ucsb1hjn8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ucsb1hjn8-go 
  name: ucsb1hjn8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ucsb1hjn8-go 
